# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 480))
        MainWindow.setMaximumSize(QtCore.QSize(900, 480))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 861, 311))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 30, 631, 261))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setHorizontalSpacing(30)
        self.formLayout_7.setVerticalSpacing(12)
        self.formLayout_7.setObjectName("formLayout_7")
        self.flat_Model = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.flat_Model.setFont(font)
        self.flat_Model.setObjectName("flat_Model")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.flat_Model)
        self.flat_Type_List = QtWidgets.QComboBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.flat_Type_List.setFont(font)
        self.flat_Type_List.setEditable(False)
        self.flat_Type_List.setFrame(True)
        self.flat_Type_List.setObjectName("flat_Type_List")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.flat_Type_List)
        self.flat_Type = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.flat_Type.setFont(font)
        self.flat_Type.setObjectName("flat_Type")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.flat_Type)
        self.flat_Model_List = QtWidgets.QComboBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.flat_Model_List.setFont(font)
        self.flat_Model_List.setObjectName("flat_Model_List")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.flat_Model_List)
        self.address_Label = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.address_Label.setFont(font)
        self.address_Label.setObjectName("address_Label")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.address_Label)
        self.address_Box = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.address_Box.setFont(font)
        self.address_Box.setObjectName("address_Box")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.address_Box)
        self.storey_Range = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.storey_Range.setFont(font)
        self.storey_Range.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.storey_Range.setObjectName("storey_Range")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.storey_Range)
        self.storey_Range_Box = QtWidgets.QSpinBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.storey_Range_Box.setFont(font)
        self.storey_Range_Box.setObjectName("storey_Range_Box")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.storey_Range_Box)
        self.lease_Label = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lease_Label.setFont(font)
        self.lease_Label.setObjectName("lease_Label")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lease_Label)
        self.lease_Box = QtWidgets.QSpinBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lease_Box.setFont(font)
        self.lease_Box.setMinimum(1920)
        self.lease_Box.setMaximum(2100)
        self.lease_Box.setObjectName("lease_Box")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lease_Box)
        self.floor_Area = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.floor_Area.setFont(font)
        self.floor_Area.setObjectName("floor_Area")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.floor_Area)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.emtpy_spacer_Label = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.emtpy_spacer_Label.setObjectName("emtpy_spacer_Label")
        self.horizontalLayout.addWidget(self.emtpy_spacer_Label)
        self.horizontalSlider = QtWidgets.QSlider(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setWeight(50)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMaximum(999)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.formLayout_7.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.months_Label = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.months_Label.setFont(font)
        self.months_Label.setObjectName("months_Label")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.months_Label)
        self.months_Box = QtWidgets.QSpinBox(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.months_Box.setFont(font)
        self.months_Box.setObjectName("months_Box")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.months_Box)
        self.predictButton = QtWidgets.QPushButton(self.groupBox)
        self.predictButton.setGeometry(QtCore.QRect(660, 30, 181, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predictButton.setFont(font)
        self.predictButton.setObjectName("predictButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.horizontalSlider.valueChanged['int'].connect(self.label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.flat_Model.setText(_translate("MainWindow", "Flat Model"))
        self.flat_Type.setText(_translate("MainWindow", "Flat Type"))
        self.address_Label.setText(_translate("MainWindow", "Address"))
        self.storey_Range.setText(_translate("MainWindow", "Storey Range"))
        self.lease_Label.setText(_translate("MainWindow", "Lease Start Year"))
        self.floor_Area.setText(_translate("MainWindow", "Floor Area"))
        self.label.setText(_translate("MainWindow", "0"))
        self.emtpy_spacer_Label.setText(_translate("MainWindow", "  "))
        self.months_Label.setText(_translate("MainWindow", "No. of Months"))
        self.predictButton.setText(_translate("MainWindow", "Predict Price"))
